"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""


class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        """
       Be careful process unicode characters with XOR bit manipulation, need to use ord to get bit 
       representation and chr to convert back
        """
        result = ord(t[-1])
        for i in range(len(s)):
            result = result ^ ord(s[i])
            result = result ^ ord(t[i])

        return chr(result)